#------------------------------------------------------------------------------
# Copyright 2019 Robert Cowart
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#------------------------------------------------------------------------------

version: '3'
services:
  od-kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.2.0
    container_name: od-kibana
    restart: unless-stopped
    hostname: kibana
    network_mode: bridge
    ports:
      - 5601:5601/tcp
    environment:
      # Set to false to disable Console. Toggling this will cause the server to regenerate assets on the next startup,
      # which may cause a delay before pages start being served.
      # Default: true 
      #CONSOLE_ENABLED: 'true'

      # Override for cgroup cpu path when mounted in manner that is inconsistent with /proc/self/cgroup
      #CPU_CGROUP_PATH_OVERRIDE: /proc/self/cgroup

      # Override for cgroup cpuacct path when mounted in manner that is inconsistent with /proc/self/cgroup
      #CPUACCT_CGROUP_PATH_OVERRIDE: /proc/self/cgroup

      # Header names and values to send to Elasticsearch. Any custom headers cannot be overwritten by client-side
      # headers, regardless of the elasticsearch.requestHeadersWhitelist configuration.
      # Default: {}
      #ELASTICSEARCH_CUSTOMHEADERS: '{}'

      # Logs queries sent to Elasticsearch. Requires logging.verbose set to true. This is useful for seeing the query
      # DSL generated by applications that currently do not have an inspector, for example Timelion and Monitoring.
      # Default: false
      #ELASTICSEARCH_LOGQUERIES: 'false'

      # Time in milliseconds to wait for Elasticsearch to respond to pings.
      # Default: the value of the elasticsearch.requestTimeout setting
      #ELASTICSEARCH_PINGTIMEOUT: 30000

      # When this setting’s value is true Kibana uses the hostname specified in the server.host setting. When the value
      # of this setting is false, Kibana uses the hostname of the host that connects to this Kibana instance.
      # Default: true
      #ELASTICSEARCH_PRESERVEHOST: 'true'

      # List of Kibana client-side headers to send to Elasticsearch. To send no client-side headers, set this value to
      # [] (an empty list).
      # Default: [ 'authorization' ]
      #ELASTICSEARCH_REQUESTHEADERSWHITELIST: 'authorization'

      # Time in milliseconds to wait for responses from the back end or Elasticsearch. This value must be a positive
      # integer.
      # Default: 30000
      #ELASTICSEARCH_REQUESTTIMEOUT: 30000

      # Time in milliseconds for Elasticsearch to wait for responses from shards. Set to 0 to disable.
      # Default: 30000
      #ELASTICSEARCH_SHARDTIMEOUT: 30000

      # Time in milliseconds between requests to check Elasticsearch for an updated list of nodes.
      # Default: false
      #ELASTICSEARCH_SNIFFINTERVAL: 'false'

      # Attempt to find other Elasticsearch nodes on startup.
      # Default: false
      #ELASTICSEARCH_SNIFFONSTART: 'false'

      # Update the list of Elasticsearch nodes immediately following a connection fault.
      # Default: false
      #ELASTICSEARCH_SNIFFONCONNECTIONFAULT: 'false'

      # Optional settings that provide the paths to the PEM-format SSL certificate file. This file is used to verify
      # the identity of Kibana to Elasticsearch and are required when xpack.ssl.verification_mode in Elasticsearch is
      # set to either certificate or full.
      #ELASTICSEARCH_SSL_CERTIFICATE: 

      # Optional settings that provide the paths to the PEM-format SSL key file. This file is used to verify the
      # identity of Kibana to Elasticsearch and are required when xpack.ssl.verification_mode in Elasticsearch is set
      # to either certificate or full.
      #ELASTICSEARCH_SSL_KEY: 

      # Optional setting that enables you to specify a list of paths to the PEM file for the certificate authority for
      # your Elasticsearch instance.
      #ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: 

      # The passphrase that will be used to decrypt the private key. This value is optional as the key may not be
      # encrypted.
      #ELASTICSEARCH_SSL_KEYPASSPHRASE: 

      # Controls the verification of certificates presented by Elasticsearch. Valid values are none, certificate, and
      # full. full performs hostname verification, and certificate does not.
      # Default: full
      #ELASTICSEARCH_SSL_VERIFICATIONMODE: full

      # Controls whether to always present the certificate specified by elasticsearch.ssl.certificate when requested.
      # This applies to all requests to Elasticsearch, including requests that are proxied for end-users. Setting this
      # to true when Elasticsearch is using certificates to authenticate users can lead to proxied requests for
      # end-users being executed as the identity tied to the configured certificate.
      # Default: false
      #ELASTICSEARCH_SSL_ALWAYSPRESENTCERTIFICATE: 'false'

      # Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying.
      # Default: 5000
      #ELASTICSEARCH_STARTUPTIMEOUT: 5000

      # The URLs of the Elasticsearch instances to use for all your queries. All nodes listed here must be on the same
      # cluster.
      # Default: "http://localhost:9200"
      ELASTICSEARCH_URL: 'https://elasticsearch:9200'

      # If your Elasticsearch is protected with basic authentication, this setting provides the username that the
      # Kibana server uses to perform maintenance on the Kibana index at startup. Your Kibana users still need to
      # authenticate with Elasticsearch, which is proxied through the Kibana server.
      #ELASTICSEARCH_USERNAME: kibana

      # If your Elasticsearch is protected with basic authentication, this setting provides the password that the
      # Kibana server uses to perform maintenance on the Kibana index at startup. Your Kibana users still need to
      # authenticate with Elasticsearch, which is proxied through the Kibana server.
      #ELASTICSEARCH_PASSWORD: changeme

      # Header names and values to send to Elasticsearch. Any custom headers cannot be overwritten by client-side
      # headers, regardless of the elasticsearch.tribe.requestHeadersWhitelist configuration.
      # Default: {}
      #ELASTICSEARCH_TRIBE_CUSTOMHEADERS: '{}'

      # Time in milliseconds to wait for Elasticsearch to respond to pings.
      # Default: the value of the elasticsearch.tribe.requestTimeout setting
      #ELASTICSEARCH_TRIBE_PINGTIMEOUT: 30000

      # List of Kibana client-side headers to send to Elasticsearch. To send no client-side headers, set this value to
      # [] (an empty list).
      # Default: [ 'authorization' ]
      #ELASTICSEARCH_TRIBE_REQUESTHEADERSWHITELIST: 'authorization'

      # Time in milliseconds to wait for responses from the back end or Elasticsearch. This value must be a positive
      # integer.
      # Default: 30000
      #ELASTICSEARCH_TRIBE_REQUESTTIMEOUT: 30000

      # Optional settings that provide the paths to the PEM-format SSL certificate file. This file validates that your
      # Elasticsearch backend uses the same key files.
      #ELASTICSEARCH_TRIBE_SSL_CERTIFICATE: 

      # Optional settings that provide the paths to the PEM-format SSL key file. This file validates that your
      # Elasticsearch backend uses the same key files.
      #ELASTICSEARCH_TRIBE_SSL_KEY: 

      # Optional setting that enables you to specify a path to the PEM file for the certificate authority for your
      # tribe Elasticsearch instance.
      #ELASTICSEARCH_TRIBE_SSL_CERTIFICATEAUTHORITIES: 

      # The passphrase that will be used to decrypt the private key. This value is optional as the key may not be
      # encrypted.
      #ELASTICSEARCH_TRIBE_SSL_KEYPASSPHRASE: 

      # Controls the verification of certificates. Valid values are none, certificate, and full. full performs hostname
      # verification, and certificate does not.
      # Default: full
      #ELASTICSEARCH_TRIBE_SSL_VERIFICATIONMODE: full

      # Optional URL of the Elasticsearch tribe instance to use for all your queries.
      #ELASTICSEARCH_TRIBE_URL: 

      # If your Elasticsearch is protected with basic authentication, these settings provide the username and password
      # that the Kibana server uses to perform maintenance on the Kibana index at startup. Your Kibana users still need
      # to authenticate with Elasticsearch, which is proxied through the Kibana server.
      #ELASTICSEARCH_TRIBE_USERNAME: 

      # If your Elasticsearch is protected with basic authentication, these settings provide the username and password
      # that the Kibana server uses to perform maintenance on the Kibana index at startup. Your Kibana users still need
      # to authenticate with Elasticsearch, which is proxied through the Kibana server.
      #ELASTICSEARCH_TRIBE_PASSWORD:

      # The default application to load.
      # Default: "discover"
      #KIBANA_DEFAULTAPPID: 'discover'

      # Kibana uses an index in Elasticsearch to store saved searches, visualizations and dashboards. Kibana creates a
      # new index if the index doesn’t already exist.
      # Default: ".kibana"
      #KIBANA_INDEX: '.kibana'

      # Enables you specify a file where Kibana stores log output.
      # Default: stdout
      LOGGING_DEST: stdout

      # Set the value of this setting to true to suppress all logging output other than error messages.
      # Default: false
      #LOGGING_QUIET: 'true'

      # Set the value of this setting to true to suppress all logging output.
      # Default: false
      #LOGGING_SILENT: 'false'

      # Set the value of this setting to true to log all events, including system usage information and all requests.
      # Supported on Elastic Cloud Enterprise.
      # Default: false
      #LOGGING_VERBOSE: 'false'

      # Set to the canonical timezone id (e.g. US/Pacific) to log events using that timezone. A list of timezones can
      # be referenced at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
      # Default: UTC
      #LOGGING_TIMEZONE: UTC

      # Turns on or off whether layers from the Elastic Maps Service should be included in the vector and tile layer
      # option list. By turning this off, only the layers that are configured here will be included.
      # Default: true
      #MAP_INCLUDEELASTICMAPSSERVICE: 'true'

      # The path where Kibana stores persistent data not saved in Elasticsearch.
      # Default: data
      #PATH_DATA: data

      # Specifies the path where Kibana creates the process ID file.
      #PID_FILE: 

      # Set the interval in milliseconds to sample system and process performance metrics. The minimum value is 100.
      # Default: 5000
      #OPS_INTERVAL: 5000

      # Specifies additional vector layers for use in Region Map visualizations. Each layer object points to an
      # external vector file that contains a geojson FeatureCollection. Supported on Elastic Cloud Enterprise. The file
      # must use the WGS84 coordinate reference system and only include polygons. If the file is hosted on a separate
      # domain from Kibana, the server needs to be CORS-enabled so Kibana can download the file. The following example
      # shows a valid regionmap configuration.
      #
      # regionmap:
      #   includeElasticMapsService: false
      #   layers:
      #     - name: "Departments of France"
      #       url: "http://my.cors.enabled.server.org/france_departements.geojson"
      #       attribution: "INRAP"
      #       fields:
      #         - name: "department"
      #           description: "Full department name"
      #         - name: "INSEE"
      #           description: "INSEE numeric identifier"
      #
      #REGIONMAP: 

      # Mandatory. A description of the map being provided. Supported on Elastic Cloud Enterprise.
      #REGIONMAP_LAYERS[]_NAME: 

      # Mandatory. The location of the geojson file as provided by a webserver. Supported on Elastic Cloud Enterprise.
      #REGIONMAP_LAYERS[]_URL: 

      # Optional. References the originating source of the geojson file. Supported on Elastic Cloud Enterprise.
      #REGIONMAP_LAYERS[]_ATTRIBUTION: 

      # Mandatory. Each layer can contain multiple fields to indicate what properties from the geojson features you
      # wish to expose. The example above shows how to define multiple properties. Supported on Elastic Cloud
      # Enterprise.
      #REGIONMAP_LAYERS[]_FIELDS[]: 

      # Mandatory. This value is used to do an inner-join between the document stored in Elasticsearch and the geojson
      # file. e.g. if the field in the geojson is called Location and has city names, there must be a field in
      # Elasticsearch that holds the same values that Kibana can then use to lookup for the geoshape data. Supported on
      # Elastic Cloud Enterprise.
      #REGIONMAP_LAYERS[]_FIELDS[]_NAME: 

      # Mandatory. The human readable text that is shown under the Options tab when building the Region Map
      # visualization. Supported on Elastic Cloud Enterprise.
      #REGIONMAP_LAYERS[]_FIELDS[]_DESCRIPTION: 

      # Turns on or off whether layers from the Elastic Maps Service should be included in the vector layer option
      # list. Supported on Elastic Cloud Enterprise. By turning this off, only the layers that are configured here will
      # be included.
      # Default: true
      #REGIONMAP_INCLUDEELASTICMAPSSERVICE: 'true'

      # Enables you to specify a path to mount Kibana at if you are running behind a proxy. Use the
      # server.rewriteBasePath setting to tell Kibana if it should remove the basePath from requests it receives, and
      # to prevent a deprecation warning at startup. This setting cannot end in a slash (/).
      #SERVER_BASEPATH: 

      # Specifies whether Kibana should rewrite requests that are prefixed with server.basePath or require that they
      # are rewritten by your reverse proxy. This setting was effectively always false before Kibana 6.3 and will
      # default to true starting in Kibana 7.0.
      # Default: false
      #SERVER_REWRITEBASEPATH: 'false'

      # Header names and values to send on all responses to the client from the Kibana server.
      # Default: {}
      #SERVER_CUSTOMRESPONSEHEADERS: '{}'

      # This setting specifies the default route when opening Kibana. You can use this setting to modify the landing
      # page when opening Kibana.
      # Default: "/app/kibana"
      #SERVER_DEFAULTROUTE: '/app/kibana'

      # This setting specifies the host of the back end server.
      # Default: "localhost"
      SERVER_HOST: 0.0.0.0

      # The maximum payload size in bytes for incoming server requests.
      # Default: 1048576
      SERVER_MAXPAYLOADBYTES: 4194304

      # A human-readable display name that identifies this Kibana instance.
      # Default: "your-hostname"
      SERVER_NAME: kibana

      # Kibana is served by a back end server. This setting specifies the port to use.
      # Default: 5601
      SERVER_PORT: 5601

      # Enables SSL for outgoing requests from the Kibana server to the browser. When set to true,
      # server.ssl.certificate and server.ssl.key are required
      # Default: "false"
      #SERVER_SSL_ENABLED: 'false'

      # Path to the PEM-format SSL certificate file.
      #SERVER_SSL_CERTIFICATE: 

      # Path to the PEM-format SSL key file.
      #SERVER_SSL_KEY: 

      # List of paths to PEM encoded certificate files that should be trusted.
      #SERVER_SSL_CERTIFICATEAUTHORITIES: 

      # Details on the format, and the valid options, are available via the OpenSSL cipher list format documentation
      # (https://www.openssl.org/docs/man1.0.2/apps/ciphers.html#CIPHER-LIST-FORMAT)
      # Default: ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES256-GCM-SHA384, DHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-SHA256, DHE-RSA-AES128-SHA256, ECDHE-RSA-AES256-SHA384, DHE-RSA-AES256-SHA384, ECDHE-RSA-AES256-SHA256, DHE-RSA-AES256-SHA256, HIGH,!aNULL, !eNULL, !EXPORT, !DES, !RC4, !MD5, !PSK, !SRP, !CAMELLIA
      #SERVER_SSL_CIPHERSUITES: 'ECDHE-RSA-AES128-GCM-SHA256, ECDHE-ECDSA-AES128-GCM-SHA256, ECDHE-RSA-AES256-GCM-SHA384, ECDHE-ECDSA-AES256-GCM-SHA384, DHE-RSA-AES128-GCM-SHA256, ECDHE-RSA-AES128-SHA256, DHE-RSA-AES128-SHA256, ECDHE-RSA-AES256-SHA384, DHE-RSA-AES256-SHA384, ECDHE-RSA-AES256-SHA256, DHE-RSA-AES256-SHA256, HIGH,!aNULL, !eNULL, !EXPORT, !DES, !RC4, !MD5, !PSK, !SRP, !CAMELLIA'

      # The passphrase that will be used to decrypt the private key. This value is optional as the key may not be
      # encrypted.
      #SERVER_SSL_KEYPASSPHRASE: 

      # Kibana will bind to this port and redirect all http requests to https over the port configured as server.port.
      #SERVER_SSL_REDIRECTHTTPFROMPORT: 

      # An array of supported protocols with versions. Valid protocols: TLSv1, TLSv1.1, TLSv1.2
      # Default: TLSv1, TLSv1.1, TLSv1.2
      #SERVER_SSL_SUPPORTEDPROTOCOLS: 'TLSv1, TLSv1.1, TLSv1.2'

      # If authentication is enabled, setting this to true allows unauthenticated users to access the Kibana server
      # status API and status page.
      # Default: false
      #STATUS_ALLOWANONYMOUS: 'false'

      # The map attribution string. Supported on Elastic Cloud Enterprise.
      # Default: "© [Elastic Maps Service](https://www.elastic.co/elastic-maps-service)"
      #TILEMAP_OPTIONS_ATTRIBUTION: Default: '© [Elastic Maps Service](https://www.elastic.co/elastic-maps-service)'

      # The maximum zoom level. Supported on Elastic Cloud Enterprise.
      # Default: 10
      #TILEMAP_OPTIONS_MAXZOOM: 10

      # The minimum zoom level. Supported on Elastic Cloud Enterprise.
      # Default: 1
      #TILEMAP_OPTIONS_MINZOOM: 1

      # An array of subdomains used by the tile service. Supported on Elastic Cloud Enterprise. Specify the position of
      # the subdomain the URL with the token {s}.
      #TILEMAP_OPTIONS_SUBDOMAINS:

      # The URL to the tileservice that Kibana uses to display map tiles in tilemap visualizations. By default, Kibana
      # reads this url from an external metadata service, but users can still override this parameter to use their own
      # Tile Map Service. For example: "https://tiles.elastic.co/v2/default/{z}/{x}/{y}.png?elastic_tile_service_tos=
      # agree&my_app_name=kibana"
      #TILEMAP_URL: 

      # Set this value to true to allow Vega to use any URL to access external data sources and images. If false, Vega
      # can only get data from Elasticsearch.
      # Default: false
      VEGA_ENABLEEXTERNALURLS: 'true'
